//Copyright timeanddate.com 2025, do not use without permission
(function(){function w(a){a.purpose.consents[1]?(d.set("gdpr","acc"),d.set("p1",0)):(d.set("gdpr","rej"),d.set("p1",1),d.setTargeting("pfo","1"))}function k(){m=!1;k=function(){};window.consentDataReady=k;d.__logEvent("S2");n.hasEnabled()&&!d.get("p1")?(n.forEach("requestBids"),setTimeout(function(){d.send()},f.timeout+2E3)):d.send()}function F(a){function c(b){0<a?setTimeout(function(){m&&F(a-1)},1E3):d.send()}m&&("function"!=typeof window.__tcfapi?c("Step 3.6: CMP not yet found"):__tcfapi("ping",
2,function(a){if(m){var b=a&&a.cmpStatus,e=a&&"visible"!=a.displayStatus;"loaded"!=b&&"disabled"!=b&&"error"!=b||!e?c("Step 3.7b: CMP ping not ready yet (display="+(a&&a.displayStatus||"na")+", status="+(b||"na")+")"):d.push(function(){d.send()})}}))}var f=window.AdMgrCfg;if(f){var p=window.AdMgr;p=p&&p._q||[];var x=f.techs,r=f.slots||[],M=f.gdprStart||"na",N=f.logUrl,O=f.rotEmpty,G=f.pf,H=f.ppid||null,I=f.lateLoad||"",d=function(){function a(a){if(!a)return"";a=a.split("/");return a[a.length-1]||
""}function c(a,b,c){a=[(new Date).getTime()-B,a];b&&a.push(b);void 0!==c&&null!==c&&a.push(c);w.push(a)}function b(){return 0<(document.referrer||"").indexOf("timeanddate")}function u(){p||(window.jcb&&window.TADhba?(p=1,jcb(N+"&"+TADhba(),function(){})):setTimeout(u,1E3))}function e(a){googletag.cmd.push(a)}function v(a,b){b&&e(function(){var g={};g[a]=b;googletag.setConfig({targeting:g})})}function h(){if(!r){r=!0;for(var g=[],A=0;A<l.length;A++)l[A].n&&g.push(a(l[A].n));c("S4",g.join(","));v("pbv",
window.pbv);v("si",b()?"2":"1");v("gdpr",C.gdpr);G&&(d.get("p1")||v("pf",G));l.forEach(function(a){if(a.t)for(var b=0;b<a.t.length;b++){var g=a.t[b];if(("pf"!=g[0]||!d.get("p1"))&&a.S){var c={};c[g[0]]=g[1];a.S.setConfig({targeting:c})}}});e(function(){googletag.enableServices();c("42");googletag.pubads().refresh(AD.s);if(f.lateLoadOps)for(var a=0;a<f.lateLoadOps.length;a++){var b=f.lateLoadOps[a],g=AD[b.varName];g&&function(a,b){var g=function(){"refresh"===b.type?googletag.pubads().refresh([a]):
"displayRefresh"===b.type&&(googletag.display(a),window.setTimeout(function(){googletag.pubads().refresh([a])},b.delay||0))};b.delay&&"refresh"===b.type?window.setTimeout(g,b.delay):g()}(g,b)}I&&(new Function(I))()})}}function k(){if(!D){D=!0;var b=m[0];c("53",a(b.n),b.rot);e(function(){googletag.pubads().refresh([b.S])})}}function q(b){if(b.slot){var g=J(b);if(g){g.hasAd=0;g.loadedAt=Date.now();if(b.isEmpty){if(c("6N",a(g.n)),g.na){if(b=document.getElementById(g.i))b=b.parentElement;b&&("invisible"===
g.na?b.style.visibility="hidden":"remove"===g.na&&(b.style.display="none"))}}else g.hasAd=1,b=b.advertiserId?b.advertiserId:null,g.winner=b,c("6Y",a(g.n),b);if(y&&m.length&&m[0]===g)a:for(y=!1;0<t.length;)if(g=t.shift(),K(g),y)break a}}setTimeout(u,1E3)}function K(a){if(a.r<a.ro&&(a.hasAd||O)){y=!0;a.e=!a.hasAd;a.hasAd=0;D=!1;E=JSON.parse(JSON.stringify(x));a.r++;m=[a];if("invisible"===a.na){var b=document.getElementById(a.i);b&&(b=b.parentElement);b&&(b.style.visibility="")}b=""+a.r;a.e&&(b+="e");
a.S.setConfig({targeting:{rot:b}});a.rot=b;d.get("p1")?k():(setTimeout(k,(d.timeout||3E3)+2E3),n.forEach("requestBidsRefresh",a))}}function J(a){var b=null;if(a.slot)a:{a=a.slot.getAdUnitPath();for(b=0;b<l.length;b++){var c=l[b];if(c.n===a){b=c;break a}}b=null}return b}var p=0,r=0,l=[],m=[],t=[],y=!1,w=[],B=(new Date).getTime(),z=JSON.parse(JSON.stringify(x)),E=JSON.parse(JSON.stringify(x)),D=0,C={gdpr:M};addEventListener("impressionViewableRotate",function(a){a=a.detail.o;a.ro&&(y?t.push(a):K(a))},
!0);e(function(){f.hasCMP&&setTimeout(function(){F(0)},5E3);googletag.pubads().disableInitialLoad();googletag.pubads().addEventListener("slotRenderEnded",q);H&&googletag.pubads().setPublisherProvidedId(H)});return{addSlot:function(a){a.wm&&a.wm>window.innerWidth&&(a.wf.i=a.i,a=a.wf);a.r=0;a.rot="0";a.a9=function(){return{slotID:a.i,slotName:a.n,sizes:a.s}};l.push(a);if(a.css){var b=document.createElement("style");b.textContent=a.css;document.head.appendChild(b)}},slot:function(a){return l[a]},a9slot:function(a){return l[a].a9()},
gptSlot:function(a){var b=l[a];b&&e(function(){b.S=googletag.defineSlot(b.n,b.s,b.i);b.S.addService(googletag.pubads());b.c&&googletag.setConfig(b.c);AD.s.push(b.S)})},slotByGPTEvent:J,dispSlot:function(a){var b=l[a];e(function(){googletag.display(b.i)})},bidsIn:function(a){delete z[a];0==Object.keys(z).length&&h()},bidsInR:function(a){delete E[a];0==Object.keys(E).length&&k()},push:e,setTargeting:v,send:h,set:function(a,b){C[a]=b},get:function(a){return C[a]},rendered:q,isSecond:b,done:function(){return p},
getLog:function(){return w},__logEvent:c}}();window.AdMgr=d;for(var h=0;h<r.length;h++)d.addSlot(r[h]);for(h=0;h<r.length;h++)d.gptSlot(h);for(h=0;h<p.length;h++){var B=p[h],z=B[0];if(d[z])d[z](B[1])}d.__logEvent("S1");var n=function(){var a={},c={};return{register:function(b,c){a[b]=c;a[b]._name=b;a[b]._enabled=!1;a[b]._config={}},enable:function(b,d){a[b]&&(c[b]=!0,a[b]._enabled=!0,a[b]._config=d||{})},forEach:function(b){var d=Array.prototype.slice.call(arguments,1),e;for(e in c)c[e]&&a[e]&&a[e][b]&&
a[e][b].apply(a[e],d)},hasEnabled:function(){for(var a in c)if(c[a])return!0;return!1},get:function(b){return a[b]}}}();n.register("aps",{init:function(){!function(a,c,b){c[a]||(c[a]={init:function(){c[a]._Q.push(["i",arguments])},fetchBids:function(){c[a]._Q.push(["f",arguments])},setDisplayBids:function(){},targetingKeys:function(){return[]},_Q:[]})}("apstag",window,document)},setupConfig:function(){window.TADaps={b:[]};var a=this._config;a&&a.pubID&&apstag.init({pubID:a.pubID,adServer:"googletag"})},
requestBids:function(){for(var a=[],c=0;c<r.length;c++){var b=d.a9slot(c);b&&a.push(b)}window.TADaps.t=+new Date;apstag.fetchBids({slots:a,timeout:f.timeout+300,params:{adRefresh:"0"}},function(a){d.push(function(){window.TADaps.e=+new Date;apstag.setDisplayBids();AD.s.forEach(function(a){var b=0;(a=a.getTargeting("amznbid"))&&0<a.length&&(b=a[0]);window.TADaps.b.push(b)});d.__logEvent("A2");d.bidsIn("aps")})})},requestBidsRefresh:function(a){window.TADaps.t=+new Date;apstag.fetchBids({slots:[a.a9()],
timeout:f.timeout,params:{adRefresh:"1"}},function(c){d.push(function(){window.TADaps.b=[];window.TADaps.e=+new Date;if(a.S){for(var b=apstag.targetingKeys&&apstag.targetingKeys().length?apstag.targetingKeys():["amznbid","amznp","amzniid"],c={},e=0;e<b.length;e++)c[b[e]]=null;a.S.setConfig({targeting:c})}apstag.setDisplayBids();AD.s.forEach(function(a){var b=0;(a=a.getTargeting("amznbid"))&&0<a.length&&(b=a[0]);window.TADaps.b.push(b)});d.bidsInR("aps")})})},htmlAfter:function(){},debugFunctions:function(){}});
n.register("pb",{init:function(){window.pbjs=window.pbjs||{};pbjs.que=pbjs.que||[];pbjs.bidderSettings={standard:{storageAllowed:!0}}},_setAdUnitElement:function(a,c){a&&c&&(c=document.getElementById(c))&&(a.element=c)},setupConfig:function(){var a=this._config,c=f.hasCMP||!1;a&&pbjs.que.push(function(){if(a.pbjsConfig){var b=a.pbjsConfig;b.priceGranularity={buckets:[{min:0,max:4,increment:.01},{min:4,max:8,increment:.02},{min:8,max:20,increment:.05},{min:20,max:30,increment:.1},{min:30,max:50,increment:.25},
{min:50,max:100,increment:1}]};b.enableTIDs=!0;b.consistentTIDs=!0;b.enableSendAllBids=!0;b.ortb2=b.ortb2||{};b.ortb2.device=b.ortb2.device||{};b.ortb2.device.dnt="1"===navigator.doNotTrack?1:0;b.bidderSequence="fixed";b.bidderTimeout=f.timeout;pbjs.setConfig(b)}if(a.aliases){for(var d in a.aliases)a.aliases.hasOwnProperty(d)&&pbjs.aliasBidder(a.aliases[d],d);pbjs.setConfig({aliases:a.aliases})}if(a.extraConfigs)for(var e in a.extraConfigs)a.extraConfigs.hasOwnProperty(e)&&pbjs.setConfig(a.extraConfigs[e],
!0);if(a.analytics&&a.analytics.length)for(b=b&&b.userSync&&b.userSync.userIds&&b.userSync.userIds.filter(function(a){return"intentIqId"===a.name})[0],d=a.analytics.filter(function(a){return"iiqAnalytics"===a.provider})[0],b&&d&&(d.options=b.params,b.params.gamObjectReference=window.googletag),b=0;b<a.analytics.length;b++)pbjs.enableAnalytics(a.analytics[b]);!c&&window.consentDataReady&&k()})},requestBids:function(){var a=this,c=this._config;c&&c.adUnits&&Array.isArray(c.adUnits)&&0!==c.adUnits.length&&
pbjs.que.push(function(){d.get("p1")&&pbjs.setConfig({deviceAccess:!1});for(var b={},f=0;f<r.length;f++){var e=d.slot(f);e&&(b[e.n]=e.i)}f=c.adUnits.filter(function(a){return Object.prototype.hasOwnProperty.call(b,a.code)});for(e=0;e<f.length;e++)a._setAdUnitElement(f[e],b[f[e].code]);pbjs.addAdUnits(f);pbjs.requestBids({bidsBackHandler:function(){var b=0,c=0,e=pbjs.getBidResponses(),f;for(f in e)if(e.hasOwnProperty(f))for(var u=e[f].bids,h=0;h<u.length;h++)u[h].cpm&&(b++,c=Math.max(c,u[h].cpm));
d.push(function(){try{pbjs.setTargetingForGPTAsync(),d.__logEvent("P2"),a._config.outOfPageTargeting&&(new Function(a._config.outOfPageTargeting))()}catch(P){}d.bidsIn("pb")});d.setTargeting("tadbid",""+b);d.highBid=c}})})},requestBidsRefresh:function(a){if(window.pbjs){if(pbjs.adUnits)for(var c=0;c<pbjs.adUnits.length;c++)pbjs.adUnits[c].code===a.n&&this._setAdUnitElement(pbjs.adUnits[c],a.i);pbjs.requestBids({timeout:2*f.timeout,adUnitCodes:[a.n],bidsBackHandler:function(){d.push(function(){try{if(a.S){var b=
a.S.getConfig("targeting").targeting||{},c={},e;for(e in b)b.hasOwnProperty(e)&&0===e.indexOf("hb_")&&(c[e]=null);a.S.setConfig({targeting:c})}pbjs.setTargetingForGPTAsync([a.n])}catch(v){}d.bidsInR("pb")})}})}},htmlAfter:function(){if(this._config.headHtml){var a=document.createElement("div");a.innerHTML=this._config.headHtml;a=a.getElementsByTagName("script");for(var c=0;c<a.length;c++){var b=a[c],d=document.createElement("script");b.src?(d.src=b.src,d.async=!0):d.textContent=b.textContent;document.head.appendChild(d)}}},
debugFunctions:function(){window.tad_debug_pbjs_bids=function(){var a=pbjs.getBidResponses(),c;for(c in a){var b=a[c].bids;if(b)for(var d=0;d<b.length;d++){var e=b[d];e.cpm?console.log("BID:",c,e.bidder,e.size,"$"+e.cpm):console.log("No bid:",c,e.bidder,"No bid or error")}else console.log(c,"No bids")}a=pbjs.getAdserverTargeting();for(c in a)b=a[c],b.hb_pb?console.log("BID SENT IN",c,b.hb_bidder,b.hb_size,b.hb_pb):console.log("BID SENT IN",c,b)}}});for(var q in x)x[q]&&n.enable(q,f.bidderConfigs&&
f.bidderConfigs[q]||{});n.forEach("init");q=window.AdMgrSetup||{};n.forEach("setupConfig");var L=!1,t=null,m=!!f.hasCMP;window.cmpEvent=function(a,c){c&&(c=a.eventStatus,"cmpuishown"==c?(L=!0,d.__logEvent("CU")):"tcloaded"==c?L||(w(a),d.__logEvent("CL"),k()):"useractioncomplete"==c&&(w(a),t&&clearTimeout(t),t=setTimeout(function(){t=null;d.__logEvent("CC");k()},50)))};window.consentDataReady=k;f.hasCMP||k();d.push(function(){if(f.targeting){var a={};for(c in f.targeting)f.targeting.hasOwnProperty(c)&&
(a[c]=""+f.targeting[c]);googletag.setConfig({targeting:a})}if(f.outOfPageSlots)for(a=0;a<f.outOfPageSlots.length;a++){var c=f.outOfPageSlots[a];var b=!0;"isSecond"===c.condition&&(b=0<(document.referrer||"").indexOf("timeanddate"));if(b)try{var h=googletag.defineOutOfPageSlot(c.slot,googletag.enums.OutOfPageFormat[c.format]);h&&(AD[c.varName]=h,h.addService(googletag.pubads()))}catch(e){}}googletag.pubads().enableSingleRequest();d.__logEvent&&d.__logEvent("S6")});n.forEach("htmlAfter");q.after&&
q.after()}})();
